### ISSUE TITLE
External links in Caption being altered upon save

### ISSUE THREAD

**Issue by NinjaRat84** [moderntribe/image-widget#9]
Hi,

I've got an issue with external links added in the Caption area being altered upon saving.
i.e I add <a href="http://www.github.com">GIT</a>

But when pressing save, it is changes into:
<a href=\"http://www.github.com\”>GIT</a> and thus it is being seen as internal link with siteurl before actual URL.

Is there something I am missing?

Note: This is only when an editor is adding the link, when I as an administrator does it result in a working link. Also uses the "Roles" plugin and have set Editor with access to unfiltered_html.

Currently running WP 4.1 and plugin 4.1.

Best regads,
  Henric

**Comment by peterchester** [comment]
Hi NinjaRat84,

Generally it's better to post questions like this in the WordPress forum because there are many more people there who might be able to help.

I took a quick look and I think what's happening is that we're relying on WordPress's wp_get_attachment_image function which strips all tags out of the caption.

You might be able to hook into the 'wp_get_attachment_image_attributes' filter to override this. Otherwise you can override the image widget output all together by making your own version of views/widget.php in your theme and make your own image html rendering function.
